# Generated by Django 5.1 on 2024-08-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.TextField()),
                ('total_price', models.FloatField()),
                ('sellable_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellable.sellable')),
            ],
        ),
    ]
